# Numerical Computing with NumPy

## Arrays of Data

### Arrays with Python Lists

In [2]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [3]:
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [4]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [5]:
m[1][0]

0.5

In [6]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [7]:
c[1][1][0]

1

In [8]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [9]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [10]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [11]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

### The Python array Class

In [12]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [13]:
import array
a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [14]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [15]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [16]:
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [17]:
a.append('string')

TypeError: must be real number, not str

In [20]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [21]:
f = open('array.apy', 'wb')
a.tofile(f)
f.close()

In [22]:
with open('array.apy', 'wb') as f:
    a.tofile(f)

In [23]:
!ls -n arr*

-rw-r--r--  1 501  20  32  1 17 21:15 array.apy


In [24]:
b = array.array('f')


In [25]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 5)

In [26]:
b

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [27]:
b = array.array('d')

In [28]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 2)

In [29]:
b

array('d', [0.0004882813645963324, 0.12500002956949174])

## Regular Numpy Arrays

### The Basics

In [30]:
import numpy as np

In [31]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [32]:
type(a)

numpy.ndarray

In [33]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], dtype='<U1')

In [34]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
a = np.arange(8, dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [36]:
a[5:]

array([5., 6., 7.])

In [37]:
a[:2]

array([0., 1.])

In [38]:
a.sum()

28.0

In [39]:
a.std()

2.29128784747792

In [40]:
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [41]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [42]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [43]:
2 * a

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [44]:
a ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [45]:
2 ** a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [46]:
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [47]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [48]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [49]:
np.sqrt(2.5)

1.5811388300841898

In [50]:
import math

In [51]:
math.sqrt(2.5)

1.5811388300841898

In [52]:
math.sqrt(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [53]:
%timeit np.sqrt(2.5)

735 ns ± 1.03 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [54]:
%timeit math.sqrt(2.5)

60.5 ns ± 0.692 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


### Multiple Dimensions

In [55]:
b = np.array([a, a * 2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [56]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [57]:
b[0, 2]

2.0

In [58]:
b[:, 1]

array([1., 2.])

In [59]:
b.sum()

84.0

In [60]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [61]:
b.sum(axis=1)

array([28., 56.])

In [62]:
c = np.zeros((2, 3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [63]:
c = np.ones((2, 3, 4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [64]:
d = np.zeros_like(c, dtype='f16', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [65]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [66]:
e = np.empty((2, 3, 2), dtype='f', order='C')
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)

In [67]:
f = np.empty_like(c)
f

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [68]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
g = np.linspace(5, 15, 12)  # 12 numbers from 5 to 15
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

### Metainformation

In [70]:
g.size

12

In [71]:
g.itemsize

8

In [72]:
g.ndim

1

In [73]:
g.shape

(12,)

In [74]:
g.dtype

dtype('float64')

In [75]:
g.nbytes

96

### Reshaping and Resizing

In [76]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
g.shape

(15,)

In [78]:
np.shape(g)

(15,)

In [79]:
g.reshape((3, 5))   # g.reshape(3, 5) also works

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [81]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [82]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [83]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
np.resize(g, (3, 1))

array([[0],
       [1],
       [2]])

In [85]:
np.resize(g, (2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
n = np.resize(g, (5, 4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [87]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [88]:
np.hstack((h, 2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [89]:
np.vstack((h, 0.5 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [90]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [91]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [94]:
for i in h.flat:
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [95]:
for i in h.ravel(order='C'):
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [96]:
for i in h.ravel(order='F'):
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

### Boolean Arrays

In [97]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [98]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [99]:
h <= 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [100]:
h == 5

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [101]:
(h == 5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [102]:
(h > 4) & (h <= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [103]:
(h > 4) & (h <= 12).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]])

In [104]:
h[h > 8]

array([ 9, 10, 11, 12, 13, 14])

In [105]:
h[(h > 4) & (h <= 12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
h[(h > 4) | (h <= 12)]  # h[(h > 4) | (h <= 12).astype(int)] does not work

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [107]:
np.where(h > 7, 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [108]:
np.where(h % 2 == 0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [109]:
np.where(h <= 7, h * 2, h / 2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

### Speed Comparison

In [110]:
import random
I = 5000

In [111]:
%time mat = [[random.gauss(0, 1) for j in range(I)] for i in range(I)]

CPU times: user 10.9 s, sys: 238 ms, total: 11.1 s
Wall time: 11.2 s


In [112]:
mat[0][:5]

[0.3116744146209233,
 1.6555659442299344,
 1.381319958969218,
 -1.1139739691260446,
 1.3123323540686083]

In [113]:
%time sum([sum(l) for l in mat])

CPU times: user 107 ms, sys: 21.5 ms, total: 129 ms
Wall time: 128 ms


-4888.423092696126

In [114]:
import sys
sum([sys.getsizeof(l) for l in mat])

209400000

In [115]:
%time mat = np.random.standard_normal((I, I))

CPU times: user 1.01 s, sys: 43.5 ms, total: 1.06 s
Wall time: 1.07 s


In [116]:
%time mat.sum()

CPU times: user 15.8 ms, sys: 12.6 ms, total: 28.4 ms
Wall time: 27.1 ms


-4100.171644597023

In [117]:
mat.nbytes

200000000

In [118]:
sys.getsizeof(mat)

200000128

### Structured Numpy Arrays

In [119]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])

In [120]:
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [121]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'], 
               'formats': 'O int float int,int'.split()})

In [122]:
dt

dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [123]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)

In [124]:
s

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [125]:
type(s)

numpy.ndarray

In [126]:
s['Name']

array(['Smith', 'Jones'], dtype=object)

In [127]:
s['Height'].mean()

1.775

In [128]:
s[0]

('Smith', 45, 1.83, (0, 1))

In [129]:
s[1]['Age']

53

## Vectorization of Code

### Basic Vectorization

In [130]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

In [131]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [132]:
s

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [133]:
r + s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [134]:
r + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [135]:
2 * r

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [136]:
2 * r + 3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [137]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [138]:
r.shape

(4, 3)

In [140]:
s = np.arange(0, 12, 4)
s

array([0, 4, 8])

In [141]:
r + s

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [143]:
s = np.arange(0, 12, 3)
s

array([0, 3, 6, 9])

In [144]:
r + s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [145]:
r.transpose() + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [146]:
sr = s.reshape(-1, 1)
sr

array([[0],
       [3],
       [6],
       [9]])

In [147]:
sr.shape

(4, 1)

In [148]:
r + s.reshape(-1, 1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [149]:
def f(x):
    return 3 * x + 5

In [150]:
f(0.5)

6.5

In [151]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

### Memory Layout

In [152]:
x = np.random.standard_normal((1000000, 5))

In [153]:
y = 2 * x + 3 # broadcasting

In [154]:
C = np.array((x, y), order='C')

In [155]:
F = np.array((x, y), order='F')

In [156]:
x = 0.0; y = 0.0

In [157]:
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [158]:
%timeit C.sum()

1.96 ms ± 18 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [159]:
%timeit F.sum()

1.96 ms ± 15.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [160]:
%timeit C.sum(axis=0)

5.87 ms ± 73.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [161]:
%timeit C.sum(axis=1)

21.5 ms ± 43.3 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [162]:
%timeit F.sum(axis=0)

49.1 ms ± 96.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [163]:
%timeit F.sum(axis=1)

43 ms ± 95.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [164]:
F = 0.0; C = 0.0